# Generated by Django 5.2.4 on 2026-04-18 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FelCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('serie', models.CharField(blank=True, max_length=20)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('fecha_certificacion', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('certificada', 'Certificada'), ('error', 'Error'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('xml_enviado', models.TextField(blank=True)),
                ('xml_respuesta', models.TextField(blank=True)),
                ('error_mensaje', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fel', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Certificación FEL',
                'verbose_name_plural': 'Certificaciones FEL',
            },
        ),
    ]
