# Generated by Django 5.2.13 on 2026-04-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_pago',
            field=models.CharField(max_length=100),
        ),
    ]
