# Generated by Django 5.2.13 on 2026-04-12 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], max_length=10)),
                ('tipo_trabajo', models.CharField(choices=[('proyecto', 'Proyecto'), ('instalacion', 'Instalación'), ('mantenimiento', 'Mantenimiento'), ('soporte', 'Soporte')], max_length=20)),
                ('tecnico_asignado', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizado', models.DateField(blank=True, null=True)),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='cotizaciones.cotizacion')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
