# Generated by Django 5.2.13 on 2026-04-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0002_ordentrabajo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='estatus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tecnico_asignado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tipo_cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tipo_trabajo',
            field=models.CharField(max_length=100),
        ),
    ]
