# Generated by Django 5.2.13 on 2026-04-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0004_ordentrabajo_campos_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='equipo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='materiales_requeridos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='notas_tecnico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='prioridad',
            field=models.CharField(blank=True, default='Media', max_length=20),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='telefono_contacto_obra',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='ubicacion_servicio',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
