# Generated by Django 5.2.4 on 2026-04-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0005_campos_equipo_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_anticipo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_oc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='metodo_anticipo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='monto_anticipo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='numero_oc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='referencia_anticipo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
