# Generated by Django 5.2.13 on 2026-04-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='asesor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estatus',
            field=models.CharField(default='Borrador', max_length=100),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
