# Generated by Django 5.2.13 on 2026-04-16 06:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizacion_asesor_alter_cotizacion_estatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='condiciones_pago',
            field=models.CharField(blank=True, help_text='Ej: Contado, Crédito 30 días', max_length=200),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='lugar_entrega',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas, términos y condiciones'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='ot_referencia',
            field=models.CharField(blank=True, help_text='Número de OT relacionada', max_length=50),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tiempo_entrega',
            field=models.CharField(blank=True, help_text='Ej: Inmediata, 1-2 semanas', max_length=200),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='validez_dias',
            field=models.PositiveIntegerField(default=30, help_text='Días de validez de la cotización'),
        ),
        migrations.AddField(
            model_name='cotizacionitem',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del ítem'),
        ),
        migrations.AddField(
            model_name='cotizacionitem',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('hora', 'Hora'), ('servicio', 'Servicio'), ('mes', 'Mes'), ('metro', 'Metro lineal'), ('m2', 'Metro cuadrado'), ('kg', 'Kilogramo'), ('litro', 'Litro'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('global', 'Global')], default='unidad', max_length=30),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5),
        ),
    ]
