# Generated by Django 5.2.13 on 2026-04-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_tipoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopago',
            name='dias_plazo',
            field=models.PositiveIntegerField(default=0, help_text='Días disponibles para realizar el pago. Use 0 para pago inmediato.'),
        ),
    ]
