# Generated by Django 5.2.4 on 2026-04-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_categoriasproducto_unidadmedida_motivosalida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaconfig',
            name='fel_api_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='API Key / Token'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='fel_api_url',
            field=models.URLField(blank=True, verbose_name='URL del API del certificador'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='fel_habilitado',
            field=models.BooleanField(default=False, verbose_name='FEL habilitado'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='fel_nis',
            field=models.CharField(blank=True, max_length=50, verbose_name='NIS / ID emisor'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='fel_proveedor',
            field=models.CharField(blank=True, help_text='Ej: INFILE, G4S, Megaprint, etc.', max_length=100, verbose_name='Proveedor certificador'),
        ),
    ]
