# Generated by Django 5.2.13 on 2026-04-17 05:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_campos_extendidos'),
        ('cotizaciones', '0004_cotizacionitem_descuentos_alter_unidad_medida'),
        ('ordenes_trabajo', '0004_ordentrabajo_campos_cierre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='cotizaciones.cotizacion')),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='ordenes_trabajo.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FacturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(default='unidad', max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('porcentaje_isr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.factura')),
            ],
        ),
    ]
