# Generated by Django 5.2.13 on 2026-04-13 08:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cod_producto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='porcentaje_utilidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
