# Generated by Django 5.2.4 on 2026-04-13 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_numero_factura_producto_orden_compra_and_more'),
        ('proveedores', '0002_alter_proveedor_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='referencia_ot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='vale_salida',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='proveedores.proveedor'),
        ),
    ]
