# Generated by Django 5.2.13 on 2026-04-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_populate_cod_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo por unidad en esta entrada (usado para calcular CPP)', max_digits=12, null=True),
        ),
    ]
