# Generated by Django 5.2.4 on 2026-04-16 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_inventario_campos_extendidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='controla_serie',
            field=models.BooleanField(default=False, help_text='Si está activo, cada unidad física requiere número de serie individual.'),
        ),
        migrations.CreateModel(
            name='UnidadSeriada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=200, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('dado_de_baja', 'Dado de Baja')], default='disponible', max_length=20)),
                ('condicion', models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('danado', 'Dañado'), ('obsoleto', 'Obsoleto')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('movimiento_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_ingresadas', to='inventario.movimientoinventario')),
                ('movimiento_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_egresadas', to='inventario.movimientoinventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Unidad Seriada',
                'verbose_name_plural': 'Unidades Seriadas',
                'ordering': ['producto', 'numero_serie'],
            },
        ),
    ]
