# Generated by Django 5.2.13 on 2026-04-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_remove_compra_cotizacion_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='num_cotizacion_proveedor',
            field=models.CharField(blank=True, help_text='Número o código de la cotización entregada por el proveedor.', max_length=100, verbose_name='N° Cotización Proveedor'),
        ),
    ]
